(require 'delight)
(delight
 '((emacs-lisp-mode "Elisp" :major)
   (aggressive-indent-mode     nil aggressive-indent)
   (company-mode               nil company)
   (eldoc-mode                 nil eldoc)
   (evil-mc-mode               nil evil-mc)
   (evil-smartparens-mode      nil evil-smartparens)
   (flycheck-mode              nil flycheck)
   (flyspell-mode              nil flyspell)
   (git-gutter+-mode           nil git-gutter+)
   (helm-mode                  nil helm-mode)
   (highlight-symbol-mode      nil highlight-symbol)
   (indent-guide-mode          nil indent-guide)
   (inertias-global-minor-mode nil inertial-scroll)
   (projectile-mode            nil projectile)
   (rainbow-mode               nil rainbow-mode)
   (smartparens-mode           nil smartparens)
   (undo-tree-mode             nil undo-tree)
   (which-key-mode             nil which-key)
   (yas-minor-mode             nil yasnippet)))
