(setq TeX-parse-self t)
(setq preview-scale-function 1.5)
(add-hook 'LaTeX-mode-hook #'auto-fill-mode)
(add-hook 'LaTeX-mode-hook #'LaTeX-math-mode)
(add-hook 'LaTeX-mode-hook #'TeX-PDF-mode)
(add-hook 'LaTeX-mode-hook #'TeX-source-correlate-mode)
