(defun color-theme-fruit ()
  "Fruit color theme based on color-theme-standard.
  "
  (interactive)
  (color-theme-standard)
  (let ((color-theme-is-cumulative t))
    (color-theme-install
     '(color-theme-fruit
       ((foreground-color . "black")
        (background-color . "gray97")
        (cursor-color . "#00e0ff"))
       (fringe ((t (:background "gray97"))))
       (region ((t (:background "gray88"))))
       (font-lock-builtin-face ((t (:foreground "#e06800"))))
       (font-lock-comment-face ((t (:foreground "#ff4080"))))
       (font-lock-constant-face ((t (:foreground "#8016ff"))))
       (font-lock-function-name-face ((t (:foreground "black"))))
       (font-lock-keyword-face ((t (:foreground "#f030d0"))))
       (font-lock-string-face ((t (:foreground "#4a9400"))))
       (font-lock-type-face ((t (:foreground "#0070e6"))))
       (font-lock-variable-name-face ((t (:foreground "black"))))
       (font-lock-warning-face ((t (:foreground "Red" :background "#ffe4e4" :bold t))))
       (modeline ((t (:foreground "white" :background "gray25"))))
       (modeline-buffer-id ((t (:foreground "white" :background "gray25"))))
       (viper-minibuffer-insert-face ((t (:foreground "black" :background "#ff4080"))))
       (elscreen-tab-background-face ((t (:background "gray60"))))
       (elscreen-tab-other-screen-face ((t (:foreground "gray40" :background "gray75"))))
       (elscreen-tab-current-screen-face ((t (:foreground "black" :background "gray97" :bold t))))))))
