(deftheme darkfruit
  "Created 2013-03-05.")

(custom-theme-set-faces
 'darkfruit
 '(cursor ((t (:background "#656565"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((t (:family "Sans Serif"))))
 '(escape-glyph ((t (:foreground "#5599ff"))))
 '(minibuffer-prompt ((t (:foreground "white"))))
 '(highlight ((t (:background "light gray"))))
 '(region ((t (:background "#444444"))))
 '(shadow ((((class color grayscale) (min-colors 88) (background light)) (:foreground "grey50")) (((class color grayscale) (min-colors 88) (background dark)) (:foreground "grey70")) (((class color) (min-colors 8) (background light)) (:foreground "green")) (((class color) (min-colors 8) (background dark)) (:foreground "yellow"))))
 '(secondary-selection ((t (:background "#272822"))))
 '(trailing-whitespace ((((class color) (background light)) (:background "red1")) (((class color) (background dark)) (:background "red1")) (t (:inverse-video t))))
 '(font-lock-builtin-face ((t (:foreground "#ff1975"))))
 '(font-lock-comment-delimiter-face ((t (:slant italic :foreground "#465457"))))
 '(font-lock-comment-face ((t (:foreground "#7f7f7f"))))
 '(font-lock-constant-face ((t (:foreground "#9955ff"))))
 '(font-lock-doc-face ((t (:foreground "#7f7f7f" :slant italic))))
 '(font-lock-function-name-face ((t (:foreground "#d9ff41" :slant italic))))
 '(font-lock-keyword-face ((t (:foreground "#ff1975"))))
 '(font-lock-negation-char-face ((t (:weight bold :foreground "#e7f6da"))))
 '(font-lock-preprocessor-face ((t (:foreground "#ffdd55"))))
 '(font-lock-regexp-grouping-backslash ((t (:weight bold))))
 '(font-lock-regexp-grouping-construct ((t (:weight bold))))
 '(font-lock-string-face ((t (:foreground "#9955ff" :slant italic))))
 '(font-lock-type-face ((t (:foreground "#55ffff"))))
 '(font-lock-variable-name-face ((t (:foreground "#d9ff41"))))
 '(font-lock-warning-face ((t (:background "#ffff00" :foreground "#000000"))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:weight bold :underline t :foreground "#8ac6f2"))))
 '(link-visited ((default (:inherit (link))) (((class color) (background light)) (:foreground "magenta4")) (((class color) (background dark)) (:foreground "violet"))))
 '(fringe ((t (:background "#232526"))))
 '(header-line ((t (:inherit mode-line :background "grey20" :foreground "grey90" :box nil))))
 '(tooltip ((((class color)) (:inherit (variable-pitch) :foreground "black" :background "lightyellow")) (t (:inherit (variable-pitch)))))
 '(mode-line ((t (:background "OliveDrab3" :foreground "dark green" :box nil :weight bold))))
 '(mode-line-buffer-id ((t (:weight semi-bold :background "#000000"))))
 '(mode-line-emphasis ((t (:background "red" :weight bold))))
 '(mode-line-highlight ((((class color) (min-colors 88)) (:box (:line-width 2 :color "grey40" :style released-button))) (t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:background "gray20" :foreground "gray50" :box nil))))
 '(powerline-active1 ((t (:background "gray34" :foreground "white"))))
 '(powerline-active2 ((t (:background "gray19" :foreground "white"))))
 '(powerline-inactive1 ((t (:background "gray15" :foreground "gray54"))))
 '(powerline-inactive2 ((t (:background "gray7" :foreground "gray35"))))
 '(isearch ((t (:background "#000000" :foreground "#C4BE89"))))
 '(isearch-fail ((t (:background "#333333" :foreground "#FFFFFF"))))
 '(lazy-highlight ((t (:foreground "black" :background "yellow"))))
 '(match ((((class color) (min-colors 88) (background light)) (:background "yellow1")) (((class color) (min-colors 88) (background dark)) (:background "RoyalBlue3")) (((class color) (min-colors 8) (background light)) (:foreground "black" :background "yellow")) (((class color) (min-colors 8) (background dark)) (:foreground "white" :background "blue")) (((type tty) (class mono)) (:inverse-video t)) (t (:background "gray"))))
 '(next-error ((t (:background "#5f0000" :foreground "#ff5555" :weight bold))))
 '(query-replace ((t (:inherit (isearch)))))
 '(default ((t (:stipple nil :background "#272727" :foreground "#FFFFFF" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal)))))

(provide-theme 'darkfruit)
